name: UPBGE daily build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
  push:
    branches:
      - main
      - 'run-ci/**'
  pull_request:

jobs:
  build_upbge:
    name: Build UPBGE
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout UPBGE sources from GitHub
        uses: actions/checkout@v2
        with:
          repository: "UPBGE/upbge"
          ref: "master"
          path: upbge-build/upbge

      - name: Install apt packages
        run: |
          sudo apt update
          sudo apt install -y python3 git libglfw3 libgles2-mesa-dev

      - name: Install dependencies
        run: |
          ./upbge-build/upbge/build_files/build_environment/install_linux_packages.py

      - name: Install libraries
        run: |
          mkdir -p ./upbge-build/lib
          cd ./upbge-build/lib
          svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/linux_x86_64_glibc_228

      - name: Build UPBGE
        run: |
          cd ./upbge-build/upbge
          make update
          make

      - name: Compress UPBGE for the artifacts
        run: |
          mkdir release
          cp -r ./upbge-build/build_linux/bin release/upbge
          cd release
          tar Jcf upbge.tar.xz upbge
          rm -rf upbge

      - name: Create MD5 checksum file
        run: |
          cd release
          md5sum upbge.tar.xz > upbge.tar.xz.md5

      - name: Upload artifact 
        uses: actions/upload-artifact@v2
        with:
          name: upbge
          path: "release"

      - name: Collect failure state
        if: failure()
        run: cp -r build failure_state

      - name: Store failure state
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: failure_state
          path: failure_state
